name: Update Build Branch

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/build-branch.yml'
      - '**.md'

jobs:
  update-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
        coverage: none
    
    - name: Install npm dependencies
      run: npm ci
    
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader
    
    - name: Build plugin
      run: npm run build
    
    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Create and push to build branch
      run: |
        # Save current commit info
        COMMIT_MSG=$(git log -1 --pretty=%B)
        COMMIT_AUTHOR=$(git log -1 --pretty="%an <%ae>")
        COMMIT_SHA=$(git rev-parse HEAD)
        
        # Create or checkout build branch
        git checkout -B build
        
        # Remove .gitignore to include build files
        rm .gitignore
        
        # Add all files including build directory
        git add -A
        
        # Check if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Commit with original author info
          git -c "user.name=$COMMIT_AUTHOR" -c "user.email=$COMMIT_AUTHOR" \
            commit -m "$COMMIT_MSG" -m "Built from commit: $COMMIT_SHA"
        fi
        
        # Force push to build branch
        git push origin build --force
    
    - name: Add build branch protection comment
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          const commit = context.payload.head_commit;
          if (commit) {
            const message = `✅ Build branch updated with compiled assets from commit ${commit.id.substring(0, 7)}`;
            console.log(message);
          }